#include <algorithm>
#include <cassert>
#include <cmath>
#include <deque>
#include <dirent.h>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <limits>
#include <list>
#include <map>
#include <set>
#include <sstream>
#include <sys/stat.h>
#include <unistd.h>
#include <vector>

#include <boost/smart_ptr/shared_array.hpp>
#include <boost/smart_ptr/shared_ptr.hpp>
