#include <algorithm>
#include <cassert>
#include <climits>
#include <cmath>
#include <deque>
#include <dirent.h>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <map>
#include <set>
#include <sstream>
#include <sys/stat.h>
#include <vector>
